### ISSUE TITLE
Cannot connect to 127.0.01:9090

### ISSUE THREAD

**Issue by mikebzh44** [timdp/kodi-missing-episodes#4]
Hello.

Sorry for opening this issue but I didn't find a thread on Kodi forum (or other place) to ask you.

I'm trying your script at my office.

I have enable JSON-RPC control : http://imgur.com/Ky70siW

I have set up your script : 

  "kodi": {
    "host": "127.0.0.1",
    "port": 9090
  },

and I also try with my IP adress : 
  "kodi": {
    "host": "172.19.4.46",
    "port": 9090
  },

but each time I run your script, I have this error :

C:\Temp\Kodi\kodi-missing-episodes-master>node kodi-missing-episodes.js
Connecting to Kodi
Error: connect ECONNREFUSED 172.19.4.46:9090
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1063:14)
From previous event:
    at kodiConnect (C:\Temp\Kodi\kodi-missing-episodes-master\kodi-missing-episo
des.js:104:6)
    at run (C:\Temp\Kodi\kodi-missing-episodes-master\kodi-missing-episodes.js:2
54:29)
    at Object.<anonymous> (C:\Temp\Kodi\kodi-missing-episodes-master\kodi-missin
g-episodes.js:263:1)

**Comment by timdp** [comment]
That doesn't look like an issue with the script.

Does `telnet localhost 9090` work? If not, either the server isn't running or some firewall is blocking access to it.

**Comment by mikebzh44** [comment]
Everything is OK now on my laptop at home ;)

**Comment by timdp** [comment]
So you got it working? Can I close this issue?

**Comment by mikebzh44** [comment]
yes, you can close this "issue"

Work fine and it's very usefull ;)

**Comment by timdp** [comment]
Cool, thanks.
