### ISSUE TITLE
No airdate and fileoutput

### ISSUE THREAD

**Issue by leothlon** [timdp/kodi-missing-episodes#5]
Hi.
it works good, but when i have: 
"includeUnaired": false,

In config i get the episodes that dont have a "planed" air date anyway.
For example http://thetvdb.com/?tab=season&seriesid=248741&seasonid=636076&lid=7
There i get episodes 15-20 as they dont have a date set.

Another feature that would be great is to output into a file rather than the console/terminal window. this makes it easy to save and such.

**Comment by timdp** [comment]
Hmm, yeah, I guess it doesn't really make sense to implicitly assume that shows without an air date have already aired. I'll fix that soon.

As for the file output: if you're only interested in saving the command of the output to some sort of log file, you can use redirection: `node kodi-missing-episodes.js >output.log`. If you're looking to ingest the output programmatically, then I'll need to add an `EventEmitter` or something that spews out e.g. JSON; at some point, I'll get around to that.

**Comment by leothlon** [comment]
Just wondering if you've had time to look into fixing the no planed air date?

**Comment by timdp** [comment]
Not yet, sorry.
